// src/emitter.js

/**
 * Emit a k6 options object containing a thresholds block derived from group stats.
 * @param {Record<string, {count,p95,...}>} groups - output from computeGroups
 * @param {number} multiplier - applied to p95 to set the threshold (default 1.5)
 * @returns {string} valid k6 JS string
 */
export function emitThresholds(groups, multiplier = 1.5) {
  const lines = [
    '// Auto-generated by har-to-k6-thresholds',
    '// https://github.com/aks-builds/har-to-k6-thresholds',
    '',
    'export const options = {',
    '  thresholds: {',
  ];

  for (const [key, stats] of Object.entries(groups)) {
    const limit = Math.round(stats.p95 * multiplier);
    lines.push(`    // ${key} — p95 baseline: ${stats.p95}ms (n=${stats.count}, ×${multiplier})`);
    lines.push(`    "http_req_duration{scenario:${sanitiseKey(key)}}": ["p(95)<${limit}"],`);
  }

  lines.push('  },', '};', '');
  return lines.join('\n');
}

/** Convert a route key like 'GET /users/{id}' into a safe k6 tag value. */
function sanitiseKey(key) {
  return key.replace(/[^a-zA-Z0-9_/-]/g, '_');
}
